Repository Snacc-Overflow/student-toolbox, pull requests merged in 2024-10, with the labels that each got.

#91 Made the To-do page mobile friendly
  src/app/auth/register/page.js
  src/app/auth/signin/page.js
  src/app/calculator/page.js
  src/app/globals.css
  src/app/register/page.js
  src/app/timetable/page.js
  src/app/todo/page.js
  src/components/Todo/TodoCreateButton.js
  src/components/Todo/TodoCreateModal.js
  src/components/Todo/styles/TodoCreateButton.css
  src/components/Todo/styles/TodoCreateModal.css
  src/components/Todo/styles/todoList.css
  src/components/Todo/styles/todoListItem.css
  src/components/auth/layout-avatar.js
  src/components/auth/styles/avatar.css
  src/components/dashboard/welcome.js
  src/components/header/header.css
  src/components/title/styles/title.css
  src/components/title/title.js
Labels: frontend

#106 Refactor ToDo Page Styling
  src/app/todo/page.js
  src/app/todo/todo.css
  src/components/Todo/TodoCreateButton.js
  src/components/Todo/TodoListItem.js
  src/components/Todo/styles/TodoCreateModal.css
  src/components/Todo/styles/todoGeneral.css
  src/components/Todo/styles/todoList.css
  src/components/Todo/styles/todoListItem.css
Labels: refactor

#104 Refactor menu
  .env
  .gitignore
  package-lock.json
  src/app/layout.js
  src/components/dashboard/dashboardItem.js
  src/components/dashboard/styles/dashboard.css
  src/components/dashboard/styles/dashboardItem.css
  src/components/dashboard/styles/welcome.css
  src/components/dashboard/welcome.js
  src/components/header/header.css
  src/components/header/nav/headerNav.css
  src/components/header/nav/link/headerLink.css
  src/components/menu/anim.js
  src/components/menu/index.js
  src/components/menu/nav/index.js
  src/components/menu/nav/link/index.js
  src/components/menu/styles/menu.css
Labels: frontend, refactor

#116 Y sun311 feat campus map
  README.md
  package.json
  public/icons/map.png
  src/app/campus/page.js
  src/app/page.js
  src/components/campus/campusMap.js
  src/components/campus/mapModal.js
  src/components/campus/placeData.js
  src/components/campus/sideBar.js
  src/components/campus/styles/campusMap.css
  src/components/menu/nav/index.js
Labels: feature, frontend

#117 fixed responsive overflow problem in tablet responsive view for campu…
  src/components/campus/sideBar.js
  src/components/campus/styles/campusMap.css
Labels: bug, frontend

#115 Mobile Friendly GPA Calculator Page
  src/app/calculator/calculator.css
  src/app/calculator/page.js
  src/components/calculator/assignment.js
  src/components/calculator/course.js
  src/components/calculator/courseHeader.js
  src/components/calculator/styles/assignment.css
  src/components/calculator/styles/course.css
  src/components/calculator/styles/courseAssignments.css
Labels: frontend
